-- ============================================================================
-- MCP Gateway — PostgreSQL schema (generated from JPA entities, Hibernate 6.6)
--
-- Apply to a fresh database:
--   psql -U postgres -d mcp_gateway -f schema.sql
--
-- The application runs with spring.jpa.hibernate.ddl-auto=validate, so the
-- schema must exist before startup. Re-generate after entity changes by
-- booting once with:
--   --spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update
--   --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
--   --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/schema-ddl.sql
-- ============================================================================

create table mcp_server (
    enabled boolean default true not null,
    id bigint generated by default as identity,
    auth_header_value varchar(2000),
    auth_token varchar(2000),
    description varchar(2000),
    auth_header_name varchar(255),
    auth_password varchar(255),
    auth_type varchar(255) default 'NONE' not null,
    auth_username varchar(255),
    base_url varchar(255) not null,
    name varchar(255) not null unique,
    transport varchar(255) default 'STREAMABLE_HTTP' not null,
    primary key (id)
);

create table gateway_tool (
    enabled boolean default true not null,
    id bigint generated by default as identity,
    server_id bigint,
    description varchar(2000),
    method varchar(255) not null,
    name varchar(255) not null,
    path varchar(255) not null,
    primary key (id)
);

-- Tool names are advertised as MCP tool names and must be unique per server
-- (also enforced at the service layer; this constraint guards against races).
alter table gateway_tool
    add constraint uk_gateway_tool_server_name unique (server_id, name);

create table gateway_tool_parameter (
    param_required boolean,
    tool_id bigint not null,
    description varchar(1000),
    data_type varchar(255),
    default_value varchar(255),
    name varchar(255),
    param_in varchar(255)
);

alter table gateway_tool
    add constraint fk_gateway_tool_server
    foreign key (server_id)
    references mcp_server;

alter table gateway_tool_parameter
    add constraint fk_gateway_tool_parameter_tool
    foreign key (tool_id)
    references gateway_tool;
